### ISSUE TITLE
Energy Total values sit over 2 registers

### ISSUE THREAD

**Issue by bcameron21** [jacauc/SunsynkEsphome#2]
Most of the energy total values sit over two registers. Your current config isn't reading these values correctly.
To read these correctly the value_type configuration parameter needs to be set to U_DWORD_R, i.e. by adding the line:
`value_type: U_DWORD_R
`

Note that your lamda filter on this totals also needs to be corrected. It doesn't need to handle the negative values.

There is one parameter (Grid Import Total) where the values aren't on consecutive registers - 78 and 80. I don't know how to configure this & would need to read up in more detail.

**Comment by Sc00bs110** [comment]
I think that it will only use the 2nd register where it goes over the max displayable on the first register.

**Comment by jacauc** [comment]
Thanks @bcameron21 - Can you give me some guidance on which specific values I need to updated to U_DWORD_R? and which ones have incorrect lambda.

Most of these calculations were inherited from @bloubul7 configs he had in Node Red, so I have no idea how/why those lambda calculations were done at the time. Happy to correct it if it simplifies the code.

Feel free to submit pull request if you want specific pieces of code updated

**Comment by jacauc** [comment]
I've updated the code accordingly - Not sure if I did it correctly, but the update seems to work okay
