### ISSUE TITLE
Overall State

### ISSUE THREAD

**Issue by chris2172** [jacauc/SunsynkEsphome#4]
Found this https://github.com/slipx06/Sunsynk-Home-Assistant-Power-Flow-Card/blob/main/animated_card_configuration_simple.txt

May help with defining the state

      return hass.states["sensor.overall_state"].state == "0" ? "blue" :
      "transparent"
    selector: '#standby'
    type: fill
  - bind: >-
      return hass.states["sensor.overall_state"].state == "1" ? "yellow" :
      "transparent"
    selector: '#selftest'
    type: fill
  - bind: >-
      return hass.states["sensor.overall_state"].state == "2" ? "green" :
      "transparent"
    selector: '#normal'
    type: fill
  - bind: >-
      return hass.states["sensor.overall_state"].state == "3" ? "orange" :
      "transparent"
    selector: '#alarm'
    type: fill
  - bind: >-
      return hass.states["sensor.overall_state"].state == "4" ? "red" :
      "transparent"
    selector: '#fault'

**Comment by jacauc** [comment]
Hi @chris2172 - I'm a little lost here. Can you provide some more information about where this code needs to be?

Feel free to submit a pull request if you want to modify code

**Comment by chris2172** [comment]
I saw it on another modbus HA plugin
In the code below you say # It is not clear what each of these states mean. TODO Fill in the string values once known
0: Standby
1: Selftest
2: Normal
3: Alarm
4: Fault

 - platform: modbus_controller          # 059 Overall State
   modbus_controller_id: sunsynk_esphome
   name: "SS Overall State"
   id: sunsynk_esphome_overall_state
   register_type: holding
   skip_updates: ${settings_skipped_updates}
   raw_encode: HEXBYTES
   address: 59
   lambda: |- # It is not clear what each of these states mean. TODO Fill in the string values once known
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      switch (value) {
        case 0: return std::string("0");
        case 1: return std::string("1");
        case 2: return std::string("2");
        case 3: return std::string("3");
        case 4: return std::string("4");
        case 5: return std::string("5");
        default: return std::string("Unknown");

**Comment by jacauc** [comment]
Ah gotcha! I follow now... thank you!
